include("initialization/body_initialization_test.jl")
include("initialization/fixed_joint_test.jl")
include("initialization/prismatic_joint_test.jl")
include("initialization/revolute_joint_test.jl")
# include("initialization/cylindrical_joint_test.jl")
# include("initialization/spherical_joint_test.jl")
# include("initialization/cylindricalfree_joint_test.jl")
# include("initialization/planar_joint_test.jl")
# include("initialization/origincon_joint_test.jl")