include(joinpath("implicit_trapezoid", "integrator.jl"))
include(joinpath("implicit_trapezoid", "body.jl"))
include(joinpath("implicit_trapezoid", "joint.jl"))
include(joinpath("implicit_trapezoid", "bound.jl"))
include(joinpath("implicit_trapezoid", "linearize.jl"))
include(joinpath("implicit_trapezoid", "test.jl"))